spring.application.name=CodeCVBackEnd
spring.datasource.url=jdbc:mysql://localhost:3306/CodeCVBackEnd
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

#server.port = 8081
spring.devtools.restart.enabled=false
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=5s